### PR TITLE
Allow Symfony 6

### LINKED ISSUE #224: Support Symfony 6
While working on some bundles I noticed I can't install `psalm/plugin-symfony` with restriction to Symfony 6.0.

```bash
❯ SYMFONY_REQUIRE=^6.0 composer update --no-progress --ansi
Loading composer repositories with package information         Restricting packages listed in "symfony/symfony" to "^6.0"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - psalm/plugin-symfony[v2.5.0, ..., v2.x-dev] require symfony/framework-bundle ^3.0 || ^4.0 || ^5.0 -> found symfony/framework-bundle[v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires psalm/plugin-symfony ^2.5 -> satisfiable by psalm/plugin-symfony[v2.5.0, v2.5.1, v2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

```

### PR DESCRIPTION
**Pull request by chalasr**
Fixes #224

### CODE REVIEW

**Comment by chalasr** [comment]
Pending https://github.com/Codeception/Codeception/pull/6273 merge. 
Thanks for the tweaks @seferov!

**Comment by tacman** [comment]
Symfony 6 will be out very soon, any chance this can be merged?  Even if it's not perfect, merely having this in composer is blocking projects using it from even testing with Symfony 6.

**Comment by ostrolucky** [comment]
What can we do to help speed up merging this? Currently, doctrine-bundle can't properly test with symfony 6 packages https://github.com/doctrine/DoctrineBundle/actions/runs/1525271516

**Review by seferov — APPROVED** [review]
@chalasr thanks for the contribution. I will try to update https://github.com/psalm/codeception-psalm-module to fix tests for Symfony 6. For now, I am merging this with failing tests

**Comment by seferov** [comment]
@chalasr @tacman @ostrolucky [v3.1.0](https://github.com/psalm/psalm-plugin-symfony/releases/tag/v3.1.0)

**Pull request merged**
