### PR TITLE
Psalm 5

### PR DESCRIPTION
**Pull request by seferov**

### CODE REVIEW

**Comment by danog** [comment]
Btw you can cherry-pick https://github.com/psalm/psalm-plugin-symfony/pull/288/commits/7a1c3fd3ffc4e0db8a2c75714b0d0d61a5a33a48 to pull in my optimization fixes if you want to finish this PR, I won't have much time today to work on the PR :)

**Comment by danog** [comment]
Have some severe doubts about how you removed those taint tests, the problem here is that Psalm is not detecting the issue (false negative), not that it shouldn't detect it (false positive).

**Comment by seferov** [comment]
> Btw you can cherry-pick [7a1c3fd](https://github.com/psalm/psalm-plugin-symfony/commit/7a1c3fd3ffc4e0db8a2c75714b0d0d61a5a33a48) to pull in my optimization fixes if you want to finish this PR, I won't have much time today to work on the PR :)

thank you very much! It seems the commit is reverting Immutable/Mutable Union types which IMO is a downgrade.

**Comment by seferov** [comment]
> Have some severe doubts about how you removed those taint tests, the problem here is that Psalm is not detecting the issue (false negative), not that it shouldn't detect it (false positive).

Taint tests are not removed except one (not removed but commented out temporarily) which does not work correctly due to Psalm bug

**Comment by danog** [comment]
Yeah, there's a psalm bug in taint detection that should be fixed before merging this MR imo

**Comment by seferov** [comment]
fixes https://github.com/psalm/psalm-plugin-symfony/issues/285

**Pull request merged**
