### PR TITLE
Suppress PropertyNotSetInConstructor error in AbstractController::$container

### PR DESCRIPTION
**Pull request by amberovsky**
It is managed by Symfony DI

### CODE REVIEW

**Comment by amberovsky** [comment]
@seferov I'm not sure if my approach with acceptance test groups is the right one (as the stub file will be applied regardless the current symfony version) - is there an idiomatic approach to _vary_ stubs content by some runtime checks ?

**Comment by seferov** [comment]
@amberovsky Thank you for the PR! 👍 

There are few notes about it:

- I think assuming highest dependency = Symfony 5 is wrong even though it is correct for now. Test suite should include Symfony versions as matrix 
- I am not sure about separating stubs/handlers by major version since new features are introduced in minor releases as well
- PropertyNotSetInConstructor issue for AbstractController is not for only Symfony 5 but also it is a case for lower versions at least for 4

**Comment by amberovsky** [comment]
@seferov I have addressed items 1 & 3 from your comment

> I am not sure about separating stubs/handlers by major version since new features are introduced in minor releases as well

Well, it does not make it **worse**? With current build/test configs you actually test only on the lowest (`3.0.0` - makes no sense to test on it, actually) & highest possible (`^5.0`) symfony versions and you restricted by not creating stubs for non-existing files in all of the `[3.00, ^5.0]` versions.
This PR allows you to not to worry about differences in major versions (for stubs) and to test on `^3.0`, `^4.0`, `^5.0`

Perhaps, for now, it is too soon to worry about the potential complexity of such separation, if there are no other better ideas - I would suggest to use it and decide on it when the time comes.

**Comment by seferov** [comment]
@amberovsky thank you!

**Pull request merged**
