### PR TITLE
Fix ParameterBag stub for Symfony 4

### LINKED ISSUE #147: ParameterBag::all has parameter, but not in Symfony 4
https://github.com/psalm/psalm-plugin-symfony/blob/master/src/Stubs/common/ParameterBag.stubphp#L27

This stub is in common, but it has to separated into a Symfony 4 and Symfony 5 case. 

the Symfony 4 ParameterBag does not have the parameter in the `all()` method: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpFoundation/ParameterBag.php#L36

### PR DESCRIPTION
**Pull request by mitelg**
Hey there :wave: 

this is my first PR for this repository. I hope I did right :slightly_smiling_face: 

This is a fix for  #147

Feedback is appreciated :+1:

### CODE REVIEW

**Comment by mitelg** [comment]
if I run the tests locally, they are successfully. I guess the failing tests are not related to my change? :thinking:

**Comment by mitelg** [comment]
ok, it is related to my change :smile: This test ist failing: https://github.com/psalm/psalm-plugin-symfony/blob/master/tests/acceptance/acceptance/Tainting.feature
I guess because it is in the @symfony-common group and I moved the stub to 4 and 5 :thinking: 

Unfortunately I have no experience with Codeception. Would be nice, if you could give me the right hints here :slightly_smiling_face:

**Comment by seferov** [comment]
Hi @mitelg, thank you for the PR.

> Unfortunately I have no experience with Codeception. Would be nice, if you could give me the right hints here 🙂

I think changing `@symfony-common` to `@symfony-5` should work in https://github.com/psalm/psalm-plugin-symfony/blob/master/tests/acceptance/acceptance/Tainting.feature#L1

**Comment by mitelg** [comment]
hey @seferov 
thanks, it did indeed the trick :+1:

**Review by seferov — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for merging 🙂👍

**Pull request merged**
