### PR TITLE
Remove AbstractTypeExtension stubs

### PR DESCRIPTION
**Pull request by zmitic**
Stubbing AbstractTypeExtension doesn't serve any purpose when multiple form types [can be extended](https://symfony.com/doc/current/form/create_form_type_extension.html#defining-the-form-type-extension) .

This PR removes templated stubs and tests.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> Stubbing AbstractTypeExtension doesn't serve any purpose when multiple form types [can be extended](https://symfony.com/doc/current/form/create_form_type_extension.html#defining-the-form-type-extension) .

Why ? The use case in the test seems still valid.

And if you use multiple forms you can still say `/** @extends AbstractTypeExtension<User> */` for
```
public static function getExtendedTypes(): iterable
{
     yield UserType::class;
     yield AnotherUserType::class;
}
```
or `/** @extends AbstractTypeExtension<User|Foo> */` for
```
public static function getExtendedTypes(): iterable
{
     yield UserType::class;
     yield FooType::class;
}
```

**Comment by zmitic** [comment]
True, I didn't think of unions.

So discard this PR?

**Comment by VincentLanglet** [comment]
> True, I didn't think of unions.
> 
> So discard this PR?

To me yes.

**Comment by zmitic** [comment]
OK, closing then.

**Pull request closed without merging**
