### PR TITLE
Add stub for Finder

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
cc @seferov :)

**Review by seferov — APPROVED** [review]
thank you @VincentLanglet

**Comment by VincentLanglet** [comment]
> thank you @VincentLanglet 

You're welcome. If you have time, a release would fix my issue :)

**Comment by seferov** [comment]
@VincentLanglet https://github.com/psalm/psalm-plugin-symfony/releases/tag/v3.0.1

**Pull request merged**
